cuda: True
ngpu: 1
gpu_id: '0'
model: 'VAMetric'
init_model: './checkpoints/VA_METRIC_DEMO_MODEL_CPU.pth'
data_dir: '/data/datasets/yt8m/Train'     # Your dataset path
video_flist: './filelists/Video_Name_List.txt'
audio_flist: './filelists/Audio_Name_List.txt'
workers: 4
batchSize: 10   # batchSize should be set as the divisor of the sample number (which is 30 in our case), such as 1, 2, 3, 5, 6, 10, 15, 30.
checkpoint_folder: './checkpoints'
topk: 5
